export enum ParameterName {
  DESITION_SCORE = 'DESITION_SCORE',
  AGE_GREATER_THAN = 'AGE_GREATER_THAN',
  IS_A_MAN = 'IS_A_MAN',
  BMI_EQUAL_OR_GREATER_THAN = 'BMI_EQUAL_OR_GREATER_THAN',
  BMI_SCORE = 'BMI_SCORE',
}
