export enum ProcessingRule {
  DATA_AS_RECEIVED = 'DATA_AS_RECEIVED',
  LESS_THAN = 'LESS_THAN',
  IQUAL_OR_LESS_THAN = 'IQUAL_OR_LESS_THAN',
  GREATER_THAN = 'GREATER_THAN',
  IQUAL_OR_GREATER_THAN = 'IQUAL_OR_GREATER_THAN',
  BETWEEN = 'BETWEEN',
}
