export enum ProcessingRuleEnum {
  // DATA_AS_RECEIVED = 'DATA_AS_RECEIVED',
  LESS_THAN = 'LESS_THAN',
  EQUAL_OR_LESS_THAN = 'EQUAL_OR_LESS_THAN',
  GREATER_THAN = 'GREATER_THAN',
  EQUAL_OR_GREATER_THAN = 'EQUAL_OR_GREATER_THAN',
  BETWEEN = 'BETWEEN',
  EQUAL = 'EQUAL',
}
